#!/bin/sh

# A hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local oid> <remote ref> <remote oid>

remote="$1"
url="$2"

zero=$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')

dirRoot="$(git rev-parse --show-toplevel)"
dirAiken="$dirRoot/onchain/aiken"

# Get the upstream branch to which we're pushing. Ignore error if none configured.
remoteBranch="$(git rev-parse --abbrev-ref --symbolic-full-name @{u} 2>/dev/null)"
# Get the main branch (usually origin/main)
mainBranch="$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/@@')"

if [ $? -eq 0 ]; then
  # If the upstream branch exists, check Aiken changes against it.
  aikenChanged=$(git diff --cached --quiet $remoteBranch -- $dirAiken)
else
  # Otherwise, check Aiken changes against the main branch. 
  aikenChanged=$(git diff --cached --quiet $mainBranch -- $dirAiken)
fi

# Skip Aiken checks if Aiken files haven't changed relative to target upstream branch
if $aikenChanged; then
    echo "Aiken files are unchanged. Skipping checks."
    exit 0
else
    echo "Aiken files have changed. Checking."
fi

cd $dirAiken

aiken build
if [ $? -ne 0 ]; then
  echo >&2 'CANCELLED PUSH: Aiken build failed'
fi

git diff --name-only --exit-code aiken.lock
if [ $? -ne 0 ]; then
  echo >&2 'CANCELLED PUSH: Aiken build produced uncommitted changes to aiken.lock'
fi

git diff --name-only --exit-code plutus.json
if [ $? -ne 0 ]; then
  echo >&2 'CANCELLED PUSH: Aiken build produced uncommitted changes to plutus.json'
fi

exit 0
