#!/usr/bin/env node
// Generates Prometheus recording + alert rules from slo/slo.json.
//
//   node slo/gen-rules.mjs
//   promtool check rules rules/*.yml
//
// Output (do not hand-edit):
//   rules/slo-recording.rules.yml
//   rules/slo-alerts.rules.yml
//
// Naming convention for generated series:
//   slo:<id>:ratio_rate<window>      ratio SLIs + availability, per window
//   slo:<id>:p<q>_<window>           latency SLIs, per quantile + window
//   slo:<id>:burn_rate<window>       error-budget burn rate (ratio SLIs)
//   slo:<id>:error_budget_remaining  fraction of the 30d budget left

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const slo = JSON.parse(readFileSync(join(here, "slo.json"), "utf8"));

const qName = (q) => `p${String(q * 100).replace(/\D/g, "")}`;
const sub = (expr, w) => expr.replaceAll("$w", w);
// YAML single-quoted scalar: only ' needs escaping; PromQL uses " for labels.
const y = (expr) => `'${expr.replaceAll("'", "''")}'`;

const header = (file) =>
  `# GENERATED by slo/gen-rules.mjs from slo/slo.json — do not edit.\n` +
  `# Regenerate:  node slo/gen-rules.mjs && promtool check rules rules/*.yml\n` +
  `# File: ${file}\n`;

const ratioSlos = slo.slos.filter((s) => s.kind === "ratio");
const latencySlos = slo.slos.filter((s) => s.kind === "latency");
const gaugeSlos = slo.slos.filter((s) => s.kind === "gauge_avg");

// ─── recording rules ─────────────────────────────────────────────────────────

const rec = [];

const ratioRuleGroup = { name: "slo_sli_ratio", rules: [] };
for (const s of ratioSlos) {
  for (const w of slo.ratioWindows) {
    const ratio = `(${sub(s.good, w)}) / (${sub(s.total, w)})`;
    const expr =
      s.ratioClampMax !== undefined
        ? `clamp_max(${ratio}, ${s.ratioClampMax})`
        : ratio;
    ratioRuleGroup.rules.push({
      record: `slo:${s.id}:ratio_rate${w}`,
      expr,
      labels: { slo: s.id, window: w },
    });
  }
}
rec.push(ratioRuleGroup);

const availGroup = { name: "slo_sli_availability", rules: [] };
for (const s of gaugeSlos) {
  for (const w of slo.ratioWindows) {
    availGroup.rules.push({
      record: `slo:${s.id}:ratio_rate${w}`,
      expr: sub(s.expr, w),
      labels: { slo: s.id, window: w },
    });
  }
}
rec.push(availGroup);

const latGroup = { name: "slo_sli_latency", rules: [] };
for (const s of latencySlos) {
  for (const w of slo.latencyWindows) {
    for (const q of slo.latencyQuantiles) {
      latGroup.rules.push({
        record: `slo:${s.id}:${qName(q)}_${w}`,
        expr: `histogram_quantile(${q}, sum by (le) (rate(${s.bucketMetric}[${w}])))`,
        labels: { slo: s.id, window: w, quantile: String(q) },
      });
    }
  }
}
rec.push(latGroup);

// error budget: burn rate per alert window + remaining budget over 30d
const burnWindows = [
  ...new Set(
    slo.burnRateAlerts.flatMap((a) => [a.longWindow, a.shortWindow]),
  ),
];
const budgetGroup = { name: "slo_error_budget", rules: [] };
for (const s of [...ratioSlos, ...gaugeSlos]) {
  const budget = 1 - s.objective;
  for (const w of burnWindows) {
    budgetGroup.rules.push({
      record: `slo:${s.id}:burn_rate${w}`,
      // `sum by (slo)` collapses to a single {slo=...} series so the
      // multi-window alerts can `and` two burn rates together (which only
      // matches on identical label sets).
      expr: `(1 - sum by (slo) (slo:${s.id}:ratio_rate${w})) / ${budget}`,
      labels: { slo: s.id },
    });
  }
  budgetGroup.rules.push({
    record: `slo:${s.id}:error_budget_remaining`,
    expr: `clamp_min(1 - ((1 - sum by (slo) (slo:${s.id}:ratio_rate${slo.errorBudgetWindow})) / ${budget}), -1)`,
    labels: { slo: s.id },
  });
}
rec.push(budgetGroup);

// ─── alert rules ─────────────────────────────────────────────────────────────

const alerts = [];

const burnAlertGroup = { name: "slo_burn_rate_alerts", rules: [] };
for (const s of [...ratioSlos, ...gaugeSlos]) {
  for (const a of slo.burnRateAlerts) {
    burnAlertGroup.rules.push({
      alert: `SLOBurnRate_${s.id}_${a.severity}`,
      expr:
        `slo:${s.id}:burn_rate${a.longWindow} > ${a.factor}` +
        ` and slo:${s.id}:burn_rate${a.shortWindow} > ${a.factor}`,
      for: a.for,
      labels: { severity: a.severity, slo: s.id },
      annotations: {
        summary: `SLO ${s.id} burning error budget fast (${a.budgetConsumed})`,
        description: `${s.description} Objective ${s.objective}. Burn rate over ${a.longWindow} and ${a.shortWindow} both exceed ${a.factor}x.`,
      },
    });
  }
}
alerts.push(burnAlertGroup);

const latAlertGroup = { name: "slo_latency_alerts", rules: [] };
for (const s of latencySlos) {
  const w = slo.latencyWindows.includes("1h") ? "1h" : slo.latencyWindows[0];
  latAlertGroup.rules.push({
    alert: `SLOLatencyHigh_${s.id}`,
    expr: `slo:${s.id}:p95_${w} > ${s.objectiveSeconds}`,
    for: "10m",
    labels: { severity: "ticket", slo: s.id },
    annotations: {
      summary: `SLO ${s.id} p95 latency above ${s.objectiveSeconds}s`,
      description: `${s.description} p95 over ${w} exceeds the ${s.objectiveSeconds}s objective.`,
    },
  });
}
alerts.push(latAlertGroup);

const availAlertGroup = { name: "slo_availability_alerts", rules: [] };
for (const s of gaugeSlos) {
  const threshold = s.alertThreshold ?? s.objective;
  availAlertGroup.rules.push({
    alert: `SLOAvailabilityLow_${s.id}`,
    expr: `min by (slo) (slo:${s.id}:ratio_rate5m) < ${threshold}`,
    for: "5m",
    labels: { severity: "page", slo: s.id },
    annotations: {
      summary: `${s.id} below ${threshold} over the last 5m`,
      description: s.description,
    },
  });
}
alerts.push(availAlertGroup);

// ─── YAML emit ───────────────────────────────────────────────────────────────

const emitRules = (groups) => {
  const lines = ["groups:"];
  for (const g of groups) {
    lines.push(`  - name: ${g.name}`);
    lines.push(`    rules:`);
    for (const r of g.rules) {
      const key = r.record ? "record" : "alert";
      lines.push(`      - ${key}: ${r.record ?? r.alert}`);
      lines.push(`        expr: ${y(r.expr)}`);
      if (r.for) lines.push(`        for: ${r.for}`);
      if (r.labels && Object.keys(r.labels).length) {
        lines.push(`        labels:`);
        for (const [k, v] of Object.entries(r.labels)) {
          lines.push(`          ${k}: ${y(String(v))}`);
        }
      }
      if (r.annotations && Object.keys(r.annotations).length) {
        lines.push(`        annotations:`);
        for (const [k, v] of Object.entries(r.annotations)) {
          lines.push(`          ${k}: ${y(String(v))}`);
        }
      }
    }
  }
  return lines.join("\n") + "\n";
};

mkdirSync(join(root, "rules"), { recursive: true });
writeFileSync(
  join(root, "rules", "slo-recording.rules.yml"),
  header("rules/slo-recording.rules.yml") + emitRules(rec),
);
writeFileSync(
  join(root, "rules", "slo-alerts.rules.yml"),
  header("rules/slo-alerts.rules.yml") + emitRules(alerts),
);

const count = (gs) => gs.reduce((n, g) => n + g.rules.length, 0);
console.log(
  `rules/slo-recording.rules.yml  ${count(rec)} rules in ${rec.length} groups`,
);
console.log(
  `rules/slo-alerts.rules.yml     ${count(alerts)} rules in ${alerts.length} groups`,
);
